--Sequence (순차적으로 증가하는 값)
SELECT * FROM USER_SEQUENCES;

--시퀀스 생성문
--CREATE SEQUENCE DEPT2_SEQ; --자동생성

CREATE SEQUENCE DEPT2_SEQ
    INCREMENT BY 1 --증가값
    START WITH 1 --시작값
    MAXVALUE 10 --최대값
    NOCACHE --캐시X
    NOCYCLE; --사이클X

CREATE TABLE DEPT2 (
    DEPT_NO NUMBER(5) PRIMARY KEY,
    DEPT_MANE VARCHAR(20),
    LOCA NUMBER(4)
    );    

DROP TABLE DEPT2;
--시퀀스의 사용

INSERT INTO DEPT2
VALUES (DEPT2_SEQ.NEXTVAL, 'TEST', 300);

INSERT INTO DEPT2
VALUES (DEPT2_SEQ.NEXTVAL, 'TEST', 300);

INSERT INTO DEPT2
VALUES (DEPT2_SEQ.NEXTVAL, 'TEST', 300);

SELECT * FROM DEPT2;

SELECT DEPT2_SEQ.CURRVAL FROM DUAL;
SELECT DEPT2_SEQ.NEXTVAL FROM DUAL;

--시퀀스의 변경 ALTER

ALTER SEQUENCE DEPT2_SEQ MAXVALUE 100000;
ALTER SEQUENCE DEPT2_SEQ INCREMENT BY 100;
ALTER SEQUENCE DEPT2_SEQ MINVALUE 1;
--ALTER TABLE DEPT2 MODIFY DEPT_NO NUMBER(5);

--시퀀스 삭제 DROP
DROP SEQUENCE DEPT2_SEQ;

--시퀀스를 다시 처음으로 되돌리는 방법
CREATE SEQUENCE DEPT2_SEQ
    INCREMENT BY 10
    NOCACHE
    NOCYCLE;

SELECT DEPT2_SEQ.NEXTVAL FROM DUAL;
--1. 현재 시퀀스 확인
SELECT DEPT2_SEQ.CURRVAL FROM DUAL;

--2. 증가값을 현재 시퀀스 -1 만큼 -
ALTER SEQUENCE DEPT2_SEQ 
    INCREMENT BY -50;

--3. 한번 NEXTVAL
SELECT DEPT2_SEQ.NEXTVAL FROM DUAL;

--4. 증가값을 1로 변경
ALTER SEQUENCE DEPT2_SEQ
    INCREMENT BY 1;

SELECT DEPT2_SEQ.NEXTVAL FROM DUAL;

--시퀀스 활용 PK 형식 : 20210408-시퀀스-참조값

CREATE TABLE DEPT3 (
    DEPT_NO VARCHAR2(30) PRIMARY KEY,
    DEPT_NAME VARCHAR2(30)
    );
    
INSERT INTO DEPT3
VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(DEPT2_SEQ.NEXTVAL, 5, 0) , 'TEST');
SELECT * FROM DEPT3;


--INDEX
--PRIMARY KEY, UNIQUE 제약조건을 사용할 때 자동으로 생성되고,
--수동으로 직접 생성할 수 있다.
--INDEX는 INDEX를 저장하는 추가적인 공간을 가지고 생성되고 조회를 빠르게 한다.
--다만, 수정, 삭제, 변경이 빈번하게 일어나는 컬럼에 적용하면 오히려 성능부하를 일으킬 수 있다.

SELECT * FROM EMPS WHERE FIRST_NAME = 'Nancy';

--EMPS의 FIRST_NAME에 INDEX 부여
CREATE INDEX EMP_FIRST_NAME_IDX ON EMPS(FIRST_NAME);


--INDEX 삭제 (INDEX는 지워지더라도 테이블에 전혀 영향을 미치지 않는다.)
DROP INDEX EMP_FIRST_NAME_IDX;